version: '3.8'

services:
  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./react:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    # command: sh -c "npm install && npm run dev -- --host"
    command: sh -c "npm install && npm run build"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
